name: pedzed.github.io
baseurl: ""

title: Ped Zed - Web ontwikkelaar
email: pedzed@outlook.com
description: >
    Op zoek naar een web ontwikkelaar? Bij mij kun je terecht voor alles op het gebied van internet.

exclude:
    - bower.json
    - LICENSE
    - README.md
sass:
    style: :compressed
